database:
  dialect: postgres
  datasource: dbname=route-engine sslmode=disable
  dir: repository/migration
  table: migrations

seed:
  dialect: postgres
  datasource: dbname=route-engine sslmode=disable
  dir: repository/seed
  table: seeds