// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        uuid.UUID
	Name      string
	Role      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	CreatedBy uuid.UUID
	UpdatedAt pgtype.Timestamp
	UpdatedBy uuid.UUID
}

type UserRole struct {
	Role string
}
