// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Courier struct {
	ID        uuid.UUID
	Name      string
	Code      string
	CreatedAt pgtype.Timestamp
	CreatedBy uuid.UUID
	UpdatedAt pgtype.Timestamp
	UpdatedBy uuid.UUID
}

type RoutingDecision struct {
	ID              uuid.UUID
	Status          string
	AllocationLogic []byte
	CreatedAt       pgtype.Timestamp
	CreatedBy       uuid.UUID
	UpdatedAt       pgtype.Timestamp
	UpdatedBy       uuid.UUID
}

type RoutingDecisionLog struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	CourierID         uuid.UUID
	RoutingDecisionID uuid.UUID
	Status            string
	Reason            pgtype.Text
	CreatedAt         pgtype.Timestamp
	CreatedBy         uuid.UUID
}
