// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Courier struct {
	ID        uuid.UUID
	Name      pgtype.Text
	Code      pgtype.Text
	CreatedAt pgtype.Timestamp
	CreatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamp
	UpdatedBy pgtype.UUID
}

type RoutingDecision struct {
	ID              uuid.UUID
	Status          string
	AllocationLogic []byte
	CreatedAt       pgtype.Timestamp
	CreatedBy       pgtype.UUID
	UpdatedAt       pgtype.Timestamp
	UpdatedBy       pgtype.UUID
}
